package com.github.jfyoteau.studycases

object Versions {
    // Android
    const val androidGradlePlugin = "7.0.0-beta05"
    const val androidMaterial = "1.4.0"

    // Jetpack
    const val androidxActivity = "1.2.3"
    const val androidxAds = "1.0.0-alpha4"
    const val androidxAnnotation = "1.2.0"
    const val androidxAnnotationExperimental = "1.1.0"
    const val androidxAppCompat = "1.3.0"
    const val androidxAppSearch = "1.0.0-alpha02"
    const val androidxArchCore = "2.1.0"
    const val androidxAsyncLayoutInflater = "1.2.3"
    const val androidxAutofill = "1.1.0"
    const val androidxBenchmark = "1.0.0"
    const val androidxBiometric = "1.1.0"
    const val androidxBrowser = "1.3.0"
    const val androidxCarApp = "1.0.0"
    const val androidxCamera = "1.0.0"
    const val androidxCameraExtensions = "1.0.0-alpha26"
    const val androidxCameraView = "1.0.0-alpha26"
    const val androidxCardView = "1.0.0"
    const val androidxCollection = "1.2.0-alpha01"
    const val androidxCompose = "1.0.0-rc01"
    const val androidxConcurrent = "1.1.0"
    const val androidxConstraintLayout = "2.0.4"
    const val androidxConstraintLayoutCompose = "1.0.0-alpha07"
    const val androidxContentPager = "1.0.0"
    const val androidxCoordinatorLayout = "1.1.0"
    const val androidxCore = "1.6.0"
    const val androidxCoreAnimation = "1.0.0-alpha02"
    const val androidxCoreGoogleShortcut = "1.0.0"
    const val androidxCoreRole = "1.0.0"
    const val androidxCoreSplashScreen = "1.0.0-alpha01"
    const val androidxCursorAdapter = "1.0.0"
    const val androidxCustomView = "1.0.0"
    const val androidxDatastore = "1.0.0-rc01"
    const val androidxDocumentFile = "1.0.1"
    const val androidxDrawerLayout = "1.1.1"
    const val androidxDynamicAnimation = "1.1.0-alpha03"
    const val androidxEmoji = "1.1.0"
    const val androidxEmoji2 = "1.0.0-alpha03"
    const val androidxEnterprise = "1.1.0"
    const val androidxExifInterface = "1.3.2"
    const val androidxFragment = "1.3.5"
    const val androidxGamesActivity = "1.0.0-beta01"
    const val androidxGamesController = "1.0.0-beta01"
    const val androidxGamesFramePacing = "1.7.0"
    const val androidxGamesTextInput = "1.0.0-beta01"
    const val androidxGamesPerfomanceTuner = "1.1.0"
    const val androidxGridLayout = "1.0.0"
    const val androidxHealth = "1.0.0-alpha01"
    const val androidxHeifWriter = "1.1.0-alpha01"
    const val androidxHilt = "1.0.0"
    const val androidxHiltNavigationCompose = "1.0.0-alpha03"
    const val androidxInterpolator = "1.0.0"
    const val androidxLeanback = "1.1.0-rc01"
    const val androidxLegacy = "1.0.0"
    const val androidxLifecycle = "2.3.1"
    const val androidxLifecycleViewModelCompose = "1.0.0-alpha07"
    const val androidxLoader = "1.0.0"
    const val androidxLocalBroadcastManager = "1.0.0"
    const val androidxMedia = "1.3.1"
    const val androidxMedia2 = "1.1.3"
    const val androidxMediaRouter = "1.2.4"
    const val androidxMultiDex = "2.0.1"
    const val androidxNavigation = "2.3.5"
    const val androidxPaging = "3.0.0"
    const val androidxPagingCompose = "1.0.0-alpha11"
    const val androidxPalette = "1.0.0"
    const val androidxPercentLayout = "1.0.0"
    const val androidxPreference = "1.1.1"
    const val androidxPrint = "1.1.0-beta01"
    const val androidxProfileInstaller = "1.0.0-rc01"
    const val androidxRecommendation = "1.0.0"
    const val androidxRecyclerView = "1.2.1"
    const val androidxRecyclerViewSelection = "1.1.0"
    const val androidxRemoteCallback = "1.0.0"
    const val androidxResourceInspection = "1.0.0-alpha03"
    const val androidxRoom = "2.3.0"
    const val androidxSavedState = "1.1.0"
    const val androidxSecurityCrypto = "1.0.0"
    const val androidxSecurityAppAuthenticator = "1.0.0-alpha02"
    const val androidxSecurityIdentityCredential = "1.0.0-alpha02"
    const val androidxShareTarget = "1.1.0"
    const val androidxSlice = "1.1.0-alpha02"
    const val androidxSlidingPanelLayout = "1.1.0"
    const val androidxStartup = "1.0.0"
    const val androidxSqlite = "2.1.0"
    const val androidxSwipeRefreshLayout = "1.1.0"
    const val androidxTest = "1.4.0"
    const val androidxTestEspresso = "3.4.0"
    const val androidxTestIntents = "3.4.0"
    const val androidxTestJunit = "1.1.3"
    const val androidxTextClassifier = "1.0.0-alpha03"
    const val androidxTracing = "1.0.0"
    const val androidxTransition = "1.4.1"
    const val androidxTvProvider = "1.1.0-alpha01"
    const val androidxVectorDrawable = "1.1.0"
    const val androidxVersionedParcelable = "1.1.0"
    const val androidxViewpager = "1.0.0"
    const val androidxViewpager2 = "1.0.0"
    const val androidxWebkit = "1.4.0"
    const val androidxWindow = "1.0.0-alpha09"
    const val androidxWork = "2.5.0"

    // Dagger
    const val dagger = "2.35"

    // Junit
    const val junit = "4.13.2"

    // Koin
    const val koin = "3.1.2"

    // Kotlin
    const val kotlin = "1.5.20"
}
